# Generated by Django 2.2.4 on 2019-08-27 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ayes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nays', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
